export type TrackingType = 'Automatic' | 'Manual' | 'Recommended';

export interface CrmTask {
  id: string;
  title: string;
  description?: string;
  priority: string;
  owner: string;
  due: string;
  dueAt?: string;
  expires?: string;
  expiresAt?: string;
  status: string;
  outcome?: string | null;
  sourceStage?: number | null;
  autoGenerated?: boolean;
}

export interface IdentitySource {
  label: string;
  detail: string;
  tone: 'blue' | 'slate' | 'green' | 'amber';
}

export interface IdentityActivity {
  title: string;
  detail: string;
  time: string;
  tracking: TrackingType;
  tone: 'blue' | 'green' | 'amber' | 'slate';
}

export interface CrmNote {
  id: string;
  body: string;
  author: string;
  time: string;
}

export interface Lead {
  id: string;
  createdAtIso: string;
  lastActivityAtIso: string;
  name: string;
  phone: string;
  source: string;
  product: string;
  stage: number;
  stageName: string;
  lastAction: string;
  nextAction: string;
  owner: string;
  priority: 'High' | 'Medium' | 'Normal';
  tracking: TrackingType;
  voucher: string;
  cartValue: string;
  age: string;
  email?: string;
  location?: string;
  firstSeen?: string;
  blocker?: string | null;
  whatsappStatus?: string | null;
  whatsappUrl?: string | null;
  whatsappMessage?: string | null;
  identityCode?: string;
  mergeConfidence?: string;
  identitySources?: IdentitySource[];
  activities?: IdentityActivity[];
  tasks?: CrmTask[];
  referrerIdentityId?: string | null;
  referrerName?: string | null;
  generation?: number | null;
  originalAmbassadorId?: string | null;
  originalAmbassadorName?: string | null;
  ownerType?: 'ambassador' | 'admin' | 'unassigned';
  ownerId?: string | null;
  nextTaskDue?: string | null;
  contactAttempts?: number;
  coolingStatus?: string;
  followupState?: 'due' | 'scheduled' | 'cold' | 'at_risk' | 'healthy' | 'customer' | 'none';
  healthState?: 'healthy' | 'at_risk' | 'cold' | 'customer';
  atRisk?: boolean;
  coldLead?: boolean;
  coldReason?: string | null;
  stageAge?: string;
  stageAgeMinutes?: number;
  expectedProgress?: string;
  coldAfter?: string;
  lastHumanContact?: string | null;
  notes?: CrmNote[];
}

export interface CrmStage {
  id: number;
  name: string;
  short: string;
  tracking: TrackingType;
}
