import { getSalesCredit } from '@/lib/sales/read-server';

const money = (value: number) => `₦${Number(value || 0).toLocaleString('en-NG', { maximumFractionDigits: 0 })}`;

export default async function SalesCreditPage() {
  const credit = await getSalesCredit();
  const now = Date.now();
  return <div className="mx-auto max-w-[1400px] space-y-5">
    <div><p className="text-xs font-black uppercase tracking-[0.16em] text-slate-400">Admin-controlled exceptions</p><h1 className="mt-2 text-3xl font-black text-[#032489]">Credit & Outstanding</h1><p className="mt-2 text-sm text-slate-500">Full payment remains the normal release rule. These are explicit approvals allowing stock handover with an outstanding balance.</p></div>
    <div className="space-y-3">{credit.map((row) => { const overdue = row.status === 'active' && new Date(row.due_at).getTime() < now; const order = row.order as { order_code?: string; customer_name?: string; customer_phone?: string; total_amount?: number; balance_due?: number } | null; return <section key={row.id} className={`rounded-2xl border bg-white p-5 shadow-sm ${overdue ? 'border-rose-300' : 'border-slate-200'}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-black text-slate-900">{order?.order_code || 'Order'} · {order?.customer_name || 'Customer'}</div><div className="mt-1 text-xs text-slate-400">{order?.customer_phone || 'No phone'} · due {new Date(row.due_at).toLocaleString('en-NG')}</div></div><span className={`rounded-full px-3 py-1 text-xs font-black ${overdue ? 'bg-rose-100 text-rose-700' : row.status === 'active' ? 'bg-amber-100 text-amber-800' : 'bg-slate-100 text-slate-600'}`}>{overdue ? 'OVERDUE' : row.status.toUpperCase()}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-3"><div className="text-[10px] font-black uppercase text-slate-400">Approved balance</div><div className="mt-1 font-black">{money(row.approved_outstanding_amount)}</div></div><div className="rounded-xl bg-slate-50 p-3"><div className="text-[10px] font-black uppercase text-slate-400">Order total</div><div className="mt-1 font-black">{money(Number(order?.total_amount || 0))}</div></div><div className="rounded-xl bg-slate-50 p-3"><div className="text-[10px] font-black uppercase text-slate-400">Reason</div><div className="mt-1 text-sm font-semibold">{row.reason}</div></div></div></section>; })}{!credit.length ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-400">No credit releases have been approved.</div> : null}</div>
  </div>;
}
