'use client';

import { useActionState, useMemo, useState } from 'react';
import { saveDraftSalesDetailsAction, type SalesActionState } from '@/app/modules/operations/sales-actions';
import { getRelevantSpecFields, ORDER_ITEM_TYPES, type OrderItemType } from '@/lib/operations/sales-model';
import type { OperationsOrder, OperationsOrderItem } from '@/lib/operations/types';
import { HelpTip } from '@/components/ui/help-tip';

const initialState:SalesActionState={success:false,message:''};
const labels:Record<string,string>={generation:'Generation',processor_type:'Processor type',processor_speed_ghz:'Processor speed (GHz)',ram:'RAM',storage_size:'Storage size',storage_type:'Storage type',screen_size:'Screen size',touchscreen:'Touchscreen?',colour:'Colour',os_installed:'OS installed',charger_included:'Charger included?',bag_included:'Bag included?',storage_capacity:'Storage capacity',network_type:'Network type',sim_type:'SIM type',accessories_included:'Accessories included',category:'Category',subcategory:'Sub-category',compatible_with:'Compatible with',system_capacity:'System capacity',brand:'Brand',model_spec:'Model / spec'};

export function DraftSalesDetails({order,item,users}:{order:OperationsOrder;item:OperationsOrderItem;users:Array<{id:string;name:string|null;email:string|null}>}){
 const [state,action,pending]=useActionState(saveDraftSalesDetailsAction,initialState);
 const [type,setType]=useState<OrderItemType>(item.item_type||order.order_type||'other');
 const [specs,setSpecs]=useState<Record<string,unknown>>(item.specs||{});
 const fields=useMemo(()=>getRelevantSpecFields(type),[type]);
 return <section className="rounded-xl border border-blue-100 bg-blue-50/40 p-5">
   <div className="flex items-center gap-2"><h2 className="text-sm font-black text-[#032489]">Sales details</h2><HelpTip text="These fields match the information EmmyTech has been keeping in the Sales Database. Only details for this kind of item are shown, so the Order stays simple." label="About Sales details" /></div>
   <form action={action} className="mt-4 space-y-4"><input type="hidden" name="order_id" value={order.id}/><input type="hidden" name="item_id" value={item.id}/><input type="hidden" name="order_type" value={type}/><input type="hidden" name="item_type" value={type}/><input type="hidden" name="specs_json" value={JSON.stringify(specs)}/>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label="Order / item type"><select value={type} onChange={e=>{setType(e.target.value as OrderItemType);setSpecs({});}} className="input">{ORDER_ITEM_TYPES.map(t=><option key={t} value={t}>{t[0].toUpperCase()+t.slice(1)}</option>)}</select></Field><Field label="Brand"><input name="brand" defaultValue={item.brand||''} className="input" /></Field><Field label="Model"><input name="model" defaultValue={item.model||''} className="input" /></Field><Field label="Condition"><input name="condition" defaultValue={item.condition||''} className="input" placeholder="Grade A – Excellent" /></Field><Field label="Internal unit cost"><input name="unit_cost_snapshot" type="number" min="0" defaultValue={item.unit_cost_snapshot??''} className="input" /></Field><Field label="Warranty period"><input name="warranty_period" defaultValue={item.warranty_period||''} className="input" placeholder="1 Month" /></Field><Field label="Warranty expiry"><input name="warranty_expires_at" type="date" defaultValue={item.warranty_expires_at||''} className="input" /></Field><Field label="Sales staff"><select name="sales_staff_user_id" className="input" defaultValue={order.sales_staff_user_id||''}><option value="">No staff selected</option>{users.map(u=><option key={u.id} value={u.id}>{u.name||u.email||u.id}</option>)}</select></Field><Field label="Sales staff name snapshot"><input name="sales_staff_name" defaultValue={order.sales_staff_name||''} className="input" placeholder="Optional display name" /></Field></div>
    {fields.length>0&&<div><p className="mb-3 text-xs font-black uppercase tracking-wide text-slate-500">{type} specifications</p><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{fields.map(key=><Field key={key} label={labels[key]||key.replaceAll('_',' ')}>{key==='touchscreen'||key==='charger_included'||key==='bag_included'?<select value={String(specs[key]??'')} onChange={e=>setSpecs(v=>({...v,[key]:e.target.value===''?null:e.target.value==='true'}))} className="input"><option value="">Not set</option><option value="true">Yes</option><option value="false">No</option></select>:<input value={String(specs[key]??'')} onChange={e=>setSpecs(v=>({...v,[key]:e.target.value}))} className="input" />}</Field>)}</div></div>}
    {state.message&&<p className={`text-sm font-bold ${state.success?'text-blue-700':'text-rose-700'}`}>{state.message}</p>}<button disabled={pending} className="rounded-lg bg-[#032489] px-4 py-2.5 text-sm font-black text-white disabled:opacity-50">{pending?'Saving...':'Save sales details'}</button>
   </form><style jsx>{`.input{width:100%;border:1px solid #e2e8f0;border-radius:8px;padding:10px 12px;font-size:14px;outline:none;background:#fff}.input:focus{border-color:#032489;box-shadow:0 0 0 3px rgba(3,36,137,.08)}`}</style>
 </section>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-1.5 block text-xs font-bold capitalize text-slate-600">{label}</span>{children}</label>}
