'use client';

import { useActionState } from 'react';
import { saveSolarInstallationAction, type SalesActionState } from '@/app/modules/operations/sales-actions';
import type { OperationsSolarInstallation } from '@/lib/operations/types';
import { HelpTip } from '@/components/ui/help-tip';

const initialState:SalesActionState={success:false,message:''};

export function SolarInstallationCard({orderId,orderItemId,installation,users}:{orderId:string;orderItemId:string;installation:OperationsSolarInstallation|null;users:Array<{id:string;name:string|null;email:string|null}>}){
 const [state,action,pending]=useActionState(saveSolarInstallationAction,initialState);
 return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
   <div className="flex items-center gap-2"><h2 className="text-sm font-black text-slate-900">Solar installation</h2><HelpTip text="A Solar sale may need installation after the Order is confirmed. This card keeps scheduling and installer details separate from the normal Order fulfilment status." label="About Solar installation" /></div>
   <form action={action} className="mt-4 space-y-4"><input type="hidden" name="order_id" value={orderId}/><input type="hidden" name="order_item_id" value={orderItemId}/><label className="flex items-center gap-3 text-sm font-bold text-slate-700"><input type="checkbox" name="installation_required" defaultChecked={installation?.installation_required??true} className="h-4 w-4"/> Installation required</label><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label="Installation address"><input name="installation_address" defaultValue={installation?.installation_address||''} className="input" /></Field><Field label="Scheduled date/time"><input name="scheduled_at" type="datetime-local" defaultValue={toLocal(installation?.scheduled_at)} className="input" /></Field><Field label="System capacity"><input name="system_capacity" defaultValue={installation?.system_capacity||''} className="input" placeholder="5kVA / 10kW" /></Field><Field label="Installation cost"><input name="installation_cost" type="number" min="0" defaultValue={installation?.installation_cost||0} className="input" /></Field><Field label="Installer"><select name="installer_user_id" defaultValue={installation?.installer_user_id||''} className="input"><option value="">No staff selected</option>{users.map(u=><option key={u.id} value={u.id}>{u.name||u.email||u.id}</option>)}</select></Field><Field label="Installer name"><input name="installer_name" defaultValue={installation?.installer_name||''} className="input" /></Field><Field label="Status"><select name="status" defaultValue={installation?.status||'pending'} className="input"><option value="not_required">Not required</option><option value="pending">Pending</option><option value="scheduled">Scheduled</option><option value="in_progress">In progress</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></Field><Field label="Notes"><input name="notes" defaultValue={installation?.notes||''} className="input" /></Field></div>{state.message&&<p className={`text-sm font-bold ${state.success?'text-blue-700':'text-rose-700'}`}>{state.message}</p>}<button disabled={pending} className="rounded-lg bg-[#032489] px-4 py-2.5 text-sm font-black text-white disabled:opacity-50">{pending?'Saving...':'Save installation'}</button></form><style jsx>{`.input{width:100%;border:1px solid #e2e8f0;border-radius:8px;padding:10px 12px;font-size:14px;outline:none;background:#fff}.input:focus{border-color:#032489;box-shadow:0 0 0 3px rgba(3,36,137,.08)}`}</style>
 </section>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-1.5 block text-xs font-bold text-slate-600">{label}</span>{children}</label>}
function toLocal(value:string|null|undefined){if(!value)return '';const d=new Date(value);const off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,16)}
