create table public.work_goals (
  id uuid primary key default gen_random_uuid(),
  title text not null check (length(trim(title)) > 0),
  description text,
  owner_id uuid not null references public.users(id) on delete cascade,
  visibility text not null check (visibility in ('personal','shared','company')),
  progress_mode text not null check (progress_mode in ('numeric','tasks')),
  start_at timestamptz,
  target_at timestamptz,
  target_value numeric,
  current_value numeric,
  unit text,
  status text not null default 'active' check (status in ('active','achieved','cancelled','archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (target_at is null or start_at is null or target_at >= start_at),
  check (progress_mode <> 'numeric' or target_value is not null)
);
create table public.work_goal_contributors (goal_id uuid not null references public.work_goals(id) on delete cascade,user_id uuid not null references public.users(id) on delete cascade,added_by uuid not null references public.users(id),created_at timestamptz not null default now(),primary key (goal_id,user_id));
create table public.work_todos (id uuid primary key default gen_random_uuid(),owner_id uuid not null references public.users(id) on delete cascade,title text not null check (length(trim(title)) > 0),notes text,priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),scheduled_for timestamptz,due_at timestamptz,goal_id uuid references public.work_goals(id) on delete set null,status text not null default 'open' check (status in ('open','completed','cancelled')),completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.work_tasks (id uuid primary key default gen_random_uuid(),title text not null check (length(trim(title)) > 0),description text,created_by uuid not null references public.users(id),source_todo_id uuid references public.work_todos(id) on delete set null,goal_id uuid references public.work_goals(id) on delete set null,priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),requested_start_at timestamptz not null,requested_due_at timestamptz not null,status text not null default 'open' check (status in ('open','cancelled','completed')),cancelled_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check (requested_due_at > requested_start_at));
create table public.work_task_assignments (id uuid primary key default gen_random_uuid(),task_id uuid not null references public.work_tasks(id) on delete cascade,assignee_id uuid not null references public.users(id),assigned_by uuid not null references public.users(id),status text not null default 'pending_acceptance' check (status in ('pending_acceptance','extension_pending','active','returned','completed','cancelled')),agreed_start_at timestamptz,agreed_due_at timestamptz,accepted_at timestamptz,completed_at timestamptz,completion_note text,rejection_reason_code text check (rejection_reason_code is null or rejection_reason_code in ('outside_authority','wrong_assignee','insufficient_information','workload_unavailable','outside_skill','other')),rejection_note text,returned_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique (task_id,assignee_id,created_at));
create table public.work_task_extension_requests (id uuid primary key default gen_random_uuid(),task_assignment_id uuid not null references public.work_task_assignments(id) on delete cascade,requested_by uuid not null references public.users(id),original_due_at timestamptz not null,proposed_due_at timestamptz not null,reason text not null check (length(trim(reason)) > 0),status text not null default 'pending' check (status in ('pending','approved','declined')),decided_by uuid references public.users(id),decided_at timestamptz,decision_note text,created_at timestamptz not null default now(),check (proposed_due_at > original_due_at));
create table public.work_task_events (id uuid primary key default gen_random_uuid(),task_id uuid not null references public.work_tasks(id) on delete cascade,task_assignment_id uuid references public.work_task_assignments(id) on delete cascade,actor_id uuid not null references public.users(id),event_type text not null check (length(trim(event_type)) > 0),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index work_todos_owner_status_idx on public.work_todos(owner_id,status,due_at); create index work_tasks_creator_idx on public.work_tasks(created_by,created_at desc); create index work_task_assignments_assignee_status_idx on public.work_task_assignments(assignee_id,status,agreed_due_at); create index work_task_assignments_task_idx on public.work_task_assignments(task_id); create index work_task_extension_requests_assignment_idx on public.work_task_extension_requests(task_assignment_id,status); create index work_task_events_task_idx on public.work_task_events(task_id,created_at); create index work_goals_owner_visibility_idx on public.work_goals(owner_id,visibility,status);
create or replace function public.work_is_internal_user(p_user_id uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.users u where u.id=p_user_id and public.is_internal_staff_role(u.role)); $$; grant execute on function public.work_is_internal_user(uuid) to authenticated;
create or replace function public.work_is_admin(p_user_id uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.users u where u.id=p_user_id and u.role in ('admin','super_admin')); $$; grant execute on function public.work_is_admin(uuid) to authenticated;
create or replace function public.work_can_read_task(p_task_id uuid,p_user_id uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public as $$ select public.work_is_admin(p_user_id) or exists(select 1 from public.work_tasks t where t.id=p_task_id and t.created_by=p_user_id) or exists(select 1 from public.work_task_assignments a where a.task_id=p_task_id and a.assignee_id=p_user_id); $$; grant execute on function public.work_can_read_task(uuid,uuid) to authenticated;
create or replace function public.work_can_read_goal(p_goal_id uuid,p_user_id uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.work_goals g where g.id=p_goal_id and (g.owner_id=p_user_id or (g.visibility='company' and public.work_is_internal_user(p_user_id)) or (g.visibility='shared' and exists(select 1 from public.work_goal_contributors c where c.goal_id=g.id and c.user_id=p_user_id)) or ((g.visibility='shared' or g.visibility='company') and public.work_is_admin(p_user_id)))); $$; grant execute on function public.work_can_read_goal(uuid,uuid) to authenticated;
alter table public.work_todos enable row level security; alter table public.work_tasks enable row level security; alter table public.work_task_assignments enable row level security; alter table public.work_task_extension_requests enable row level security; alter table public.work_task_events enable row level security; alter table public.work_goals enable row level security; alter table public.work_goal_contributors enable row level security;
create policy "owners manage their todos" on public.work_todos for all to authenticated using (auth.uid()=owner_id) with check (auth.uid()=owner_id);
create policy "participants read tasks" on public.work_tasks for select to authenticated using (public.work_can_read_task(id,auth.uid()));
create policy "participants read task assignments" on public.work_task_assignments for select to authenticated using (public.work_can_read_task(task_id,auth.uid()));
create policy "participants read extension requests" on public.work_task_extension_requests for select to authenticated using (exists(select 1 from public.work_task_assignments a where a.id=task_assignment_id and public.work_can_read_task(a.task_id,auth.uid())));
create policy "participants read task events" on public.work_task_events for select to authenticated using (public.work_can_read_task(task_id,auth.uid()));
create policy "permitted users read goals" on public.work_goals for select to authenticated using (public.work_can_read_goal(id,auth.uid()));
create policy "goal owners create goals" on public.work_goals for insert to authenticated with check (owner_id=auth.uid() and public.work_is_internal_user(auth.uid()) and (visibility<>'company' or public.work_is_admin(auth.uid())));
create policy "goal owners manage non-company goals" on public.work_goals for update to authenticated using ((owner_id=auth.uid() and visibility in ('personal','shared')) or (visibility='company' and public.work_is_admin(auth.uid()))) with check ((owner_id=auth.uid() and visibility in ('personal','shared')) or (visibility='company' and public.work_is_admin(auth.uid())));
create policy "goal owners delete non-company goals" on public.work_goals for delete to authenticated using ((owner_id=auth.uid() and visibility in ('personal','shared')) or (visibility='company' and public.work_is_admin(auth.uid())));
create policy "permitted users read goal contributors" on public.work_goal_contributors for select to authenticated using (public.work_can_read_goal(goal_id,auth.uid()));
create policy "goal owners manage contributors" on public.work_goal_contributors for all to authenticated using (exists(select 1 from public.work_goals g where g.id=goal_id and (g.owner_id=auth.uid() or public.work_is_admin(auth.uid())))) with check (exists(select 1 from public.work_goals g where g.id=goal_id and (g.owner_id=auth.uid() or public.work_is_admin(auth.uid()))));
revoke insert,update,delete on public.work_tasks from authenticated; revoke insert,update,delete on public.work_task_assignments from authenticated; revoke insert,update,delete on public.work_task_extension_requests from authenticated; revoke insert,update,delete on public.work_task_events from authenticated;
grant select,insert,update,delete on public.work_todos to authenticated; grant select on public.work_tasks to authenticated; grant select on public.work_task_assignments to authenticated; grant select on public.work_task_extension_requests to authenticated; grant select on public.work_task_events to authenticated; grant select,insert,update,delete on public.work_goals to authenticated; grant select,insert,update,delete on public.work_goal_contributors to authenticated;
