"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import {
  Activity,
  ArrowLeft,
  Bell,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleUserRound,
  Clock3,
  ContactRound,
  Gauge,
  ListTodo,
  MessageCircle,
  NotebookPen,
  Search,
  Sparkles,
  Target,
  Users,
  Zap,
  X,
  Mail,
  ArrowUpRight,
} from "lucide-react";
import styles from "./crm-workspace.module.css";

type ViewKey = "dashboard" | "leads" | "funnel" | "contacts" | "tasks" | "notes" | "handoff";
type TrackingType = "Automatic" | "Manual" | "Recommended";

type CrmTask = {
  id: string;
  title: string;
  description?: string;
  priority: string;
  owner: string;
  due: string;
  dueAt?: string;
  expires?: string;
  expiresAt?: string;
  status: string;
  outcome?: string | null;
  sourceStage?: number | null;
  autoGenerated?: boolean;
};

type Lead = {
  id: string;
  name: string;
  phone: string;
  source: string;
  product: string;
  stage: number;
  stageName: string;
  lastAction: string;
  nextAction: string;
  owner: string;
  priority: "High" | "Medium" | "Normal";
  tracking: TrackingType;
  voucher: string;
  cartValue: string;
  age: string;
  email?: string;
  location?: string;
  firstSeen?: string;
  blocker?: string | null;
  whatsappStatus?: string | null;
  whatsappUrl?: string | null;
  whatsappMessage?: string | null;
  identityCode?: string;
  mergeConfidence?: string;
  identitySources?: IdentitySource[];
  activities?: IdentityActivity[];
  tasks?: CrmTask[];
  referrerIdentityId?: string | null;
  referrerName?: string | null;
  generation?: number | null;
  originalAmbassadorId?: string | null;
  originalAmbassadorName?: string | null;
  ownerType?: "ambassador" | "admin" | "unassigned";
  ownerId?: string | null;
  nextTaskDue?: string | null;
  contactAttempts?: number;
  coolingStatus?: string;
  followupState?: "due" | "scheduled" | "cold" | "at_risk" | "healthy" | "customer" | "none";
  healthState?: "healthy" | "at_risk" | "cold" | "customer";
  atRisk?: boolean;
  coldLead?: boolean;
  coldReason?: string | null;
  stageAge?: string;
  stageAgeMinutes?: number;
  expectedProgress?: string;
  coldAfter?: string;
  lastHumanContact?: string | null;
  notes?: { id: string; body: string; author: string; time: string }[];
};

const stages = [
  { id: 1, name: "Awareness", short: "Spin", tracking: "Automatic" as TrackingType },
  { id: 2, name: "Interest", short: "Voucher claim", tracking: "Automatic" as TrackingType },
  { id: 3, name: "Consideration", short: "Browse / ask", tracking: "Automatic" as TrackingType },
  { id: 4, name: "Intent", short: "Added to cart", tracking: "Automatic" as TrackingType },
  { id: 5, name: "Purchase", short: "WhatsApp handoff", tracking: "Manual" as TrackingType },
  { id: 6, name: "Onboarding", short: "Paid / delivery", tracking: "Manual" as TrackingType },
  { id: 7, name: "Satisfaction", short: "Feedback / review", tracking: "Manual" as TrackingType },
  { id: 8, name: "Loyalty", short: "Repeat buyer", tracking: "Manual" as TrackingType },
  { id: 9, name: "Expansion", short: "Cross-sell ready", tracking: "Recommended" as TrackingType },
  { id: 10, name: "Advocacy", short: "Qualified referral", tracking: "Manual" as TrackingType },
];

type IdentitySource = { label: string; detail: string; tone: "blue" | "slate" | "green" | "amber" };

type IdentityActivity = {
  title: string;
  detail: string;
  time: string;
  tracking: TrackingType;
  tone: "blue" | "green" | "amber" | "slate";
};

function identityProfile(lead: Lead) {
  return {
    email: lead.email ?? "â€”",
    location: lead.location ?? "â€”",
    firstSeen: lead.firstSeen ?? "â€”",
    lastSeen: lead.age,
    mergeConfidence: lead.mergeConfidence ?? "Identity links from Supabase",
    sources: lead.identitySources?.length
      ? lead.identitySources
      : [{ label: "CRM", detail: lead.id.slice(0, 8).toUpperCase(), tone: "blue" as const }],
  };
}

const stageActivityCopy: Record<number, { title: string; detail: string; tracking: TrackingType; tone: "blue" | "green" | "amber" | "slate" }> = {
  1: { title: "Spin completed", detail: "Identity captured from first tracked Spin Wheel interaction.", tracking: "Automatic", tone: "blue" },
  2: { title: "Voucher claimed", detail: "Voucher was attached to the same identity after verification.", tracking: "Automatic", tone: "green" },
  3: { title: "Product interest detected", detail: "Product views, searches or enquiries moved the identity into consideration.", tracking: "Automatic", tone: "blue" },
  4: { title: "Product added to cart", detail: "Cart activity confirms stronger purchase intent.", tracking: "Automatic", tone: "green" },
  5: { title: "WhatsApp handoff", detail: "Customer clicked Send to EmmyTech. Conversation outcome is now a manual blind spot.", tracking: "Manual", tone: "amber" },
  6: { title: "Payment / delivery confirmed", detail: "Staff manually confirmed the purchase and moved the identity into onboarding.", tracking: "Manual", tone: "green" },
  7: { title: "Post-sale follow-up", detail: "Feedback, review or satisfaction status is recorded manually.", tracking: "Manual", tone: "blue" },
  8: { title: "Repeat purchase recorded", detail: "The same identity has returned and is now treated as a loyal customer.", tracking: "Manual", tone: "green" },
  9: { title: "Cross-sell opportunity", detail: "Known purchase history triggered a recommended next product or bundle.", tracking: "Recommended", tone: "amber" },
  10: { title: "Advocacy qualification", detail: "Qualified referred purchases make this identity eligible for Ambassador review.", tracking: "Manual", tone: "blue" },
};

function identityActivities(lead: Lead): IdentityActivity[] {
  if (lead.activities?.length) return lead.activities;
  const data = stageActivityCopy[lead.stage];
  return data
    ? [{ ...data, title: lead.lastAction, time: lead.age }]
    : [];
}

function TrackingBadge({ type }: { type: TrackingType }) {
  return <span className={`${styles.trackingBadge} ${styles[type.toLowerCase()]}`}>{type}</span>;
}

function friendlyActionError(raw: string) {
  const message = raw || "CRM action failed";
  if (message.includes("crm_tasks_status_check")) return "Could not update this task. Refresh the CRM and try again.";
  if (message.includes("foreign key constraint")) return "This customer record is not fully linked yet. Refresh and try again.";
  if (message.includes("check constraint")) return "That update is not allowed yet. Refresh the CRM and try again.";
  if (message.trim().startsWith("{") || message.length > 180) return "The CRM could not save this change. Please try again.";
  return message;
}

export default function CrmWorkspace() {
  const [view, setView] = useState<ViewKey>("dashboard");
  const [query, setQuery] = useState("");
  const [selectedLead, setSelectedLead] = useState<Lead | null>(null);
  const [leads, setLeads] = useState<Lead[]>([]);
  const [loading, setLoading] = useState(true);
  const [dbError, setDbError] = useState<string | null>(null);
  const [reloadToken, setReloadToken] = useState(0);
  const [actionFeedback, setActionFeedback] = useState<string | null>(null);

  useEffect(() => {
    let active = true;
    async function load() {
      try {
        setLoading(true);
        const response = await fetch("/api/crm/identities", { cache: "no-store" });
        const payload = await response.json();
        if (!response.ok) throw new Error(payload.detail || payload.error || "CRM database request failed");
        if (active) {
          const nextLeads = payload.leads ?? [];
          setLeads(nextLeads);
          setSelectedLead((current) => current ? nextLeads.find((lead: Lead) => lead.id === current.id) ?? current : null);
          setDbError(null);
        }
      } catch (error) {
        if (active) setDbError(error instanceof Error ? error.message : "Unable to load CRM database");
      } finally {
        if (active) setLoading(false);
      }
    }
    load();
    return () => { active = false; };
  }, [reloadToken]);

  async function performAction(payload: Record<string, unknown>) {
    const response = await fetch("/api/crm/action", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ...payload, actor: "Administrator" }),
    });
    const result = await response.json();
    if (!response.ok) {
      const rawMessage = result.detail || result.error || "CRM action failed";
      const message = friendlyActionError(rawMessage);
      console.error("CRM action failed:", rawMessage);
      setActionFeedback(message);
      window.setTimeout(() => setActionFeedback(null), 3200);
      return { ok: false, message };
    }
    setActionFeedback(result.message || "Saved");
    setReloadToken((value) => value + 1);
    window.setTimeout(() => setActionFeedback(null), 2600);
    return result;
  }

  async function moveLead(lead: Lead, toStage: number) {
    if (toStage === lead.stage) return;
    await performAction({ action: "move_stage", identityId: lead.id, fromStage: lead.stage, toStage });
  }

  async function addNote(lead: Lead, note: string) {
    await performAction({ action: "add_note", identityId: lead.id, note });
  }

  async function recordOutcome(lead: Lead, outcome: string) {
    await performAction({ action: "whatsapp_outcome", identityId: lead.id, fromStage: lead.stage, outcome });
  }

  async function recordTaskOutcome(lead: Lead, task: CrmTask, outcome: string) {
    await performAction({ action: "task_outcome", identityId: lead.id, taskId: task.id, outcome });
  }

  const filteredLeads = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return leads;
    return leads.filter((lead) =>
      [lead.name, lead.phone, lead.product, lead.source, lead.stageName, lead.owner, lead.referrerName, lead.originalAmbassadorName]
        .join(" ")
        .toLowerCase()
        .includes(q),
    );
  }, [query, leads]);

  const handoffs = leads.filter((lead) => lead.stage === 5);
  const attention = leads.filter((lead) => lead.followupState === "due");
  const customers = leads.filter((lead) => lead.stage >= 6).length;
  const openTasks = leads.reduce((sum, lead) => sum + (lead.tasks?.filter((task) => task.status === "open").length ?? 0), 0);

  const navItems: { key: ViewKey; label: string; icon: typeof Gauge; count?: number }[] = [
    { key: "dashboard", label: "Dashboard", icon: Gauge },
    { key: "leads", label: "Leads", icon: Users, count: leads.length },
    { key: "funnel", label: "Funnel", icon: Target },
    { key: "contacts", label: "Contacts", icon: ContactRound },
    { key: "tasks", label: "Tasks", icon: ListTodo, count: openTasks },
    { key: "notes", label: "Notes", icon: NotebookPen },
    { key: "handoff", label: "WhatsApp Handoff", icon: MessageCircle, count: handoffs.length },
  ];

  return (
    <div className={styles.shell}>
      <aside className={styles.sidebar}>
        <div className={styles.logoCard}>
          <Image src="/branding/emmytech-logo.png" alt="Emmy Technology" width={170} height={56} className={styles.logo} priority />
        </div>

        <div className={styles.workspaceBadge}>
          <Target size={15} />
          <span>CRM Workspace</span>
        </div>

        <nav className={styles.nav}>
          {navItems.map((item) => {
            const Icon = item.icon;
            return (
              <button
                key={item.key}
                type="button"
                onClick={() => setView(item.key)}
                className={`${styles.navLink} ${view === item.key ? styles.active : ""}`}
              >
                <Icon size={18} />
                <span>{item.label}</span>
                {item.count ? <em>{item.count}</em> : null}
              </button>
            );
          })}
        </nav>

        <div className={styles.sidebarDivider} />

        <Link href="/" className={styles.backLink}>
          <ArrowLeft size={17} />
          <span>Company Overview</span>
        </Link>

        <div className={styles.sidebarUser}>
          <div className={styles.sidebarAvatar}>AD</div>
          <div>
            <strong>Administrator</strong>
            <span>CRM access</span>
          </div>
          <ChevronRight size={16} />
        </div>
      </aside>

      <div className={styles.workspace}>
        <header className={styles.topbar}>
          <div>
            <div className={styles.eyebrow}>CRM WORKSPACE</div>
            <div className={styles.topTitle}>{navItems.find((item) => item.key === view)?.label ?? "CRM"}</div>
          </div>
          <div className={styles.topActions}>
            <div className={styles.globalSearch}>
              <Search size={16} />
              <input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search leads, products, phone..." />
            </div>
            <button className={styles.iconButton} aria-label="Notifications"><Bell size={19} /></button>
            <div className={styles.profileCard}>
              <div className={styles.profileAvatar}><CircleUserRound size={18} /></div>
              <div><strong>Administrator</strong><span>Admin</span></div>
            </div>
          </div>
        </header>

        <main className={styles.content}>
          {loading ? <div className={styles.dbState}>Loading CRM data...</div> : null}
          {dbError ? <div className={`${styles.dbState} ${styles.dbError}`}>Database connection error: {dbError}</div> : null}
          {!loading && !dbError && view === "dashboard" && (
            <Dashboard leads={leads} attention={attention.length} handoffs={handoffs.length} customers={customers} onOpenLead={setSelectedLead} />
          )}
          {!loading && !dbError && view === "leads" && <LeadTable leads={filteredLeads} onOpenLead={setSelectedLead} />}
          {!loading && !dbError && view === "funnel" && <FunnelBoard leads={filteredLeads} onOpenLead={setSelectedLead} onMoveLead={moveLead} />}
          {!loading && !dbError && view === "contacts" && <ContactsView leads={filteredLeads} onOpenLead={setSelectedLead} />}
          {!loading && !dbError && view === "tasks" && <TasksView leads={leads} onOpenLead={setSelectedLead} onTaskOutcome={recordTaskOutcome} />}
          {!loading && !dbError && view === "notes" && <NotesView leads={leads} onOpenLead={setSelectedLead} />}
          {!loading && !dbError && view === "handoff" && <HandoffView leads={handoffs} onOpenLead={setSelectedLead} onOutcome={recordOutcome} />}
        </main>
      </div>
      {actionFeedback ? <div className={styles.actionToast}>{actionFeedback}</div> : null}
      {selectedLead ? <LeadDetailDrawer lead={selectedLead} onClose={() => setSelectedLead(null)} onMoveStage={moveLead} onAddNote={addNote} onTaskOutcome={recordTaskOutcome} /> : null}
    </div>
  );
}

function PageIntro({ title, copy, tag }: { title: string; copy: string; tag?: string }) {
  return (
    <section className={styles.pageIntro}>
      <div>
        <h1>{title}</h1>
        <p>{copy}</p>
      </div>
      {tag ? <div className={styles.darkTag}><Activity size={14} />{tag}</div> : null}
    </section>
  );
}

function Dashboard({ leads, attention, handoffs, customers, onOpenLead }: { leads: Lead[]; attention: number; handoffs: number; customers: number; onOpenLead: (lead: Lead) => void }) {
  const stageCounts = stages.map((stage) => ({ ...stage, count: leads.filter((lead) => lead.stage === stage.id).length }));

  return (
    <>
      <PageIntro title="CRM Command Centre" copy="See where every prospect is, what happened last, and the next action most likely to move them forward." tag="Hybrid tracking" />

      <section className={styles.filterBar}>
        <div className={styles.filterIcon}><Clock3 size={19} /></div>
        <div className={styles.filterCopy}><strong>Customer journey overview</strong><span>Behavior moves people forward. Manual checkpoints are clearly marked.</span></div>
        <button className={styles.periodButton}>Last 30 days <ChevronDown size={16} /></button>
      </section>

      <section className={styles.metricsGrid}>
        <Metric label="Total people" value={String(leads.length)} helper="Across all CRM stages" icon={<Users size={20} />} tone="blue" />
        <Metric label="Need attention" value={String(attention)} helper="Actions due now" icon={<Zap size={20} />} tone="orange" />
        <Metric label="WhatsApp handoffs" value={String(handoffs)} helper="Outcome requires manual update" icon={<MessageCircle size={20} />} tone="green" />
        <Metric label="Customers" value={String(customers)} helper="Paid / onboarding and beyond" icon={<CheckCircle2 size={20} />} tone="purple" />
      </section>

      <section className={styles.panel}>
        <div className={styles.panelHeader}>
          <div><h2>Customer journey</h2><p>Tracked from first spin through advocacy.</p></div>
          <div className={styles.legend}><TrackingBadge type="Automatic" /><TrackingBadge type="Manual" /><TrackingBadge type="Recommended" /></div>
        </div>
        <div className={styles.journeyFunnel} aria-label="Customer journey funnel">
          {stageCounts.map((stage, index) => (
            <div
              className={styles.funnelStage}
              key={stage.id}
              style={{ width: `${100 - index * 4}%` }}
            >
              <div className={styles.funnelStageLeft}>
                <span className={styles.funnelNumber}>{stage.id}</span>
                <div><strong>{stage.name}</strong><small>{stage.short}</small></div>
              </div>
              <div className={styles.funnelStageRight}>
                <b>{stage.count}</b>
                <span>{stage.tracking}</span>
              </div>
            </div>
          ))}
        </div>
      </section>

      <div className={styles.twoColumn}>
        <section className={styles.panel}>
          <div className={styles.panelHeader}><div><h2>Needs attention</h2><p>The system should tell staff what to do next.</p></div><button className={styles.linkButton}>View all <ChevronRight size={15} /></button></div>
          <div className={styles.attentionList}>
            {leads.filter((lead) => lead.followupState === "due").map((lead) => (
              <button type="button" className={styles.attentionRow} key={lead.id} onClick={() => onOpenLead(lead)}>
                <div className={styles.attentionIcon}><Sparkles size={18} /></div>
                <div className={styles.attentionCopy}><strong>{lead.name}</strong><span>{lead.stageName} Â· {lead.product}</span><p>{lead.coldLead ? (lead.coldReason || "Cold lead â€” recovery needed") : lead.atRisk ? `At risk Â· ${lead.stageAge || ""} in stage` : lead.nextAction}</p></div>
                <div className={styles.attentionMeta}><TrackingBadge type={lead.tracking} /><span>{lead.age}</span><ChevronRight size={15} /></div>
              </button>
            ))}
          </div>
        </section>

        <section className={styles.panel}>
          <div className={styles.panelHeader}><div><h2>Tracking boundaries</h2><p>What the OS knows vs. what staff must confirm.</p></div></div>
          <div className={styles.boundaryList}>
            <Boundary tone="green" title="Automatic" copy="Spin, voucher claim, product browse, add to cart and WhatsApp button click." />
            <Boundary tone="blue" title="Manual" copy="WhatsApp outcome, payment confirmation, delivery, feedback and post-sale relationship." />
            <Boundary tone="amber" title="Recommended" copy="Next-best-action, cross-sell timing and win-back prompts generated from known behavior." />
          </div>
        </section>
      </div>
    </>
  );
}

function Metric({ label, value, helper, icon, tone }: { label: string; value: string; helper: string; icon: ReactNode; tone: string }) {
  return <div className={styles.metricCard}><div className={`${styles.metricIcon} ${styles[tone]}`}>{icon}</div><div><span>{label}</span><strong>{value}</strong><p>{helper}</p></div></div>;
}

function Boundary({ tone, title, copy }: { tone: string; title: string; copy: string }) {
  return <div className={styles.boundaryRow}><div className={`${styles.boundaryDot} ${styles[tone]}`} /><div><strong>{title}</strong><p>{copy}</p></div></div>;
}

function LeadTable({ leads, onOpenLead }: { leads: Lead[]; onOpenLead: (lead: Lead) => void }) {
  const [filter, setFilter] = useState<"all" | "due" | "risk" | "cold" | "customers">("all");

  const counts = {
    all: leads.length,
    due: leads.filter((lead) => lead.followupState === "due").length,
    risk: leads.filter((lead) => lead.atRisk).length,
    cold: leads.filter((lead) => lead.coldLead).length,
    customers: leads.filter((lead) => lead.stage >= 6).length,
  };

  const visibleLeads = leads.filter((lead) => {
    if (filter === "due") return lead.followupState === "due";
    if (filter === "risk") return Boolean(lead.atRisk);
    if (filter === "cold") return Boolean(lead.coldLead);
    if (filter === "customers") return lead.stage >= 6;
    return true;
  });

  return (
    <>
      <PageIntro title="Leads & Customers" copy="A clean view of each person, where they are in the journey, and whether human action is required now." tag={`${leads.length} records`} />

      <div className={styles.leadFilters}>
        <button type="button" onClick={() => setFilter("all")} className={filter === "all" ? styles.leadFilterActive : ""}>All <span>{counts.all}</span></button>
        <button type="button" onClick={() => setFilter("due")} className={filter === "due" ? styles.leadFilterActive : ""}>Action due <span>{counts.due}</span></button>
        <button type="button" onClick={() => setFilter("risk")} className={`${filter === "risk" ? styles.leadFilterActive : ""} ${styles.riskFilter}`}>At risk <span>{counts.risk}</span></button>
        <button type="button" onClick={() => setFilter("cold")} className={`${filter === "cold" ? styles.leadFilterActive : ""} ${styles.coldFilter}`}>Cold leads <span>{counts.cold}</span></button>
        <button type="button" onClick={() => setFilter("customers")} className={filter === "customers" ? styles.leadFilterActive : ""}>Customers <span>{counts.customers}</span></button>
      </div>

      <section className={`${styles.panel} ${styles.leadDirectoryPanel}`}>
        <div className={styles.leadDirectoryHead}>
          <span>Customer</span>
          <span>Stage</span>
          <span>Interest</span>
          <span>Last activity</span>
          <span>Owner</span>
          <span>Status</span>
          <span />
        </div>

        <div className={styles.leadDirectory}>
          {visibleLeads.length ? visibleLeads.map((lead) => {
            const dueTask = (lead.tasks ?? []).find((task) => task.status.toLowerCase() === "open");
            const state = lead.stage >= 6 ? "customer" : lead.coldLead ? "cold" : lead.atRisk ? "at_risk" : lead.followupState || "healthy";

            return (
              <button type="button" className={styles.leadDirectoryRow} key={lead.id} onClick={() => onOpenLead(lead)}>
                <div className={styles.leadPerson}>
                  <span className={styles.leadMiniAvatar}>{lead.name.split(" ").map((part) => part[0]).slice(0, 2).join("")}</span>
                  <span><strong>{lead.name}</strong><small>{lead.phone}</small></span>
                </div>

                <div className={styles.leadJourney}>
                  <b>{lead.stage}</b>
                  <span><strong>{lead.stageName}</strong><small>{lead.tracking}</small></span>
                </div>

                <div className={styles.leadInterest}><strong>{lead.product}</strong><small>{lead.source}</small></div>
                <div className={styles.leadActivity}><strong>{lead.lastAction}</strong><small>{lead.age} ago</small></div>
                <div className={styles.leadOwner}>{lead.owner}</div>

                <div className={styles.leadFollowup}>
                  {state === "due" && dueTask ? (
                    <>
                      <span className={styles.dueNowDot} />
                      <span><strong>{dueTask.title}</strong><small>{dueTask.due}{dueTask.expires ? ` Â· ${dueTask.expires}` : ""}</small></span>
                    </>
                  ) : state === "scheduled" ? (
                    <span className={`${styles.followupPill} ${styles.followupScheduled}`}>Scheduled</span>
                  ) : state === "at_risk" ? (
                    <span className={`${styles.followupPill} ${styles.followupRisk}`}>At risk Â· {lead.stageAge || "stalled"}</span>
                  ) : state === "cold" ? (
                    <span className={`${styles.followupPill} ${styles.followupCold}`}>Cold Â· {lead.stageAge || "stalled"}</span>
                  ) : state === "customer" ? (
                    <span className={`${styles.followupPill} ${styles.followupCustomer}`}>Customer</span>
                  ) : (
                    <span className={`${styles.followupPill} ${styles.followupHealthy}`}>Healthy Â· {lead.stageAge || "new"}</span>
                  )}
                </div>

                <ChevronRight className={styles.leadRowChevron} size={17} />
              </button>
            );
          }) : <div className={styles.leadDirectoryEmpty}>No records in this view.</div>}
        </div>
      </section>
    </>
  );
}

function FunnelBoard({ leads, onOpenLead, onMoveLead }: { leads: Lead[]; onOpenLead: (lead: Lead) => void; onMoveLead: (lead: Lead, stage: number) => Promise<void> }) {
  return (
    <>
      <PageIntro title="Behavior Funnel" copy="Drag a person between stages when staff needs to confirm or correct the journey. Every manual move is saved to CRM history." tag="10 stages" />
      <section className={styles.funnelLegend}><TrackingBadge type="Automatic" /><span>system event</span><TrackingBadge type="Manual" /><span>staff confirmation</span><TrackingBadge type="Recommended" /><span>system suggestion</span></section>
      <section className={styles.kanbanWrap}>
        <div className={styles.kanban}>
          {stages.map((stage) => {
            const cards = leads.filter((lead) => lead.stage === stage.id);
            return <div
              className={styles.kanbanColumn}
              key={stage.id}
              onDragOver={(event) => event.preventDefault()}
              onDrop={(event) => {
                event.preventDefault();
                const id = event.dataTransfer.getData("text/plain");
                const lead = leads.find((item) => item.id === id);
                if (lead) void onMoveLead(lead, stage.id);
              }}
            >
              <div className={styles.kanbanHead}><div><span>{stage.id}</span><strong>{stage.name}</strong></div><b>{cards.length}</b></div>
              <p className={styles.kanbanSub}>{stage.short}</p>
              <TrackingBadge type={stage.tracking} />
              <div className={styles.kanbanCards}>{cards.length ? cards.map((lead) => <LeadCard key={lead.id} lead={lead} onOpen={() => onOpenLead(lead)} />) : <div className={styles.emptyStage}>Drop a record here</div>}</div>
            </div>;
          })}
        </div>
      </section>
    </>
  );
}

function LeadCard({ lead, onOpen }: { lead: Lead; onOpen: () => void }) {
  return <button
    type="button"
    className={styles.leadCard}
    draggable
    onDragStart={(event) => { event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("text/plain", lead.id); }}
    onClick={onOpen}
    title="Open identity or drag to another stage"
  ><div className={styles.leadCardTop}><strong>{lead.name}</strong><span className={`${styles.priority} ${styles[lead.priority.toLowerCase()]}`}>{lead.priority}</span></div><p>{lead.product}</p><div className={styles.cardInfo}><span>Last</span><b>{lead.lastAction}</b></div><div className={styles.nextBox}><Sparkles size={14} /><div><span>Action status</span><strong>{lead.nextAction}</strong></div></div><footer><span>{lead.owner}</span><span className={styles.openHint}>Open <ArrowUpRight size={12} /></span></footer></button>;
}

function ContactsView({ leads, onOpenLead }: { leads: Lead[]; onOpenLead: (lead: Lead) => void }) {
  return <><PageIntro title="Contacts" copy="People are stored once, while funnel stage, activities and commercial history build around the same profile." tag={`${leads.length} contacts`} /><section className={styles.contactGrid}>{leads.map((lead) => <button type="button" className={styles.contactCard} key={lead.id} onClick={() => onOpenLead(lead)}><div className={styles.contactAvatar}>{lead.name.split(" ").map((part) => part[0]).slice(0,2).join("")}</div><div><h3>{lead.name}</h3><p>{lead.phone}</p><span>{lead.product}</span></div><ChevronRight size={18} /></button>)}</section></>;
}

function TasksView({ leads, onOpenLead, onTaskOutcome }: { leads: Lead[]; onOpenLead: (lead: Lead) => void; onTaskOutcome: (lead: Lead, task: CrmTask, outcome: string) => Promise<void> }) {
  const tasks = leads.flatMap((lead) =>
    (lead.tasks ?? []).map((task) => ({ ...task, lead })),
  );

  const isOpen = (task: (typeof tasks)[number]) => task.status.toLowerCase() === "open";
  const sortByDue = (a: (typeof tasks)[number], b: (typeof tasks)[number]) => {
    const aTime = a.dueAt ? new Date(a.dueAt).getTime() : Number.MAX_SAFE_INTEGER;
    const bTime = b.dueAt ? new Date(b.dueAt).getTime() : Number.MAX_SAFE_INTEGER;
    return aTime - bTime;
  };

  const openTasks = tasks.filter(isOpen).sort(sortByDue);
  const closedTasks = tasks.filter((task) => !isOpen(task)).sort((a, b) => sortByDue(b, a)).slice(0, 10);

  const renderTask = (task: (typeof tasks)[number], openTask: boolean) => (
    <article className={`${styles.taskCard} ${openTask ? "" : styles.taskCardClosed}`} key={task.id}>
      <button type="button" className={styles.taskMain} onClick={() => onOpenLead(task.lead)}>
        <span className={`${styles.taskStatusDot} ${openTask ? styles.taskOpen : styles.taskDone}`} />
        <span className={styles.taskCopy}>
          <span className={styles.taskTitleLine}>
            <strong>{task.title}</strong>
            <b className={`${styles.priority} ${styles[task.priority.toLowerCase()]}`}>{task.priority}</b>
          </span>
          <span className={styles.taskSubline}>
            <span>{task.lead.name}</span>
            <span>â€¢</span>
            <span>{task.due}</span>
            {task.expires ? <><span>â€¢</span><span className={styles.taskExpiry}>{task.expires}</span></> : null}
            <span>â€¢</span>
            <span>{task.owner}</span>
          </span>
          <span className={styles.taskDescription}>{task.description || "Take the required follow-up action and record the outcome."}</span>
        </span>
      </button>

      {openTask ? (
        <div className={styles.taskActions}>
          <button type="button" onClick={() => void onTaskOutcome(task.lead, task, "Contacted")}>Contacted</button>
          <button type="button" onClick={() => void onTaskOutcome(task.lead, task, "No response")}>No response</button>
          <button type="button" className={styles.taskCompleteButton} onClick={() => void onTaskOutcome(task.lead, task, "Completed")}>Complete</button>
        </div>
      ) : (
        <span className={styles.taskOutcome}>{task.outcome || task.status}</span>
      )}
    </article>
  );

  return <>
    <PageIntro title="Tasks & Follow-ups" copy="Only actionable follow-ups appear here. The CRM waits for the right contact window and avoids back-to-back chasing." tag={`${openTasks.length} open`} />

    <section className={styles.taskWorkspace}>
      <div className={styles.taskSectionHeader}>
        <div><h3>Needs action</h3><p>Due follow-ups, ordered by urgency.</p></div>
        <span>{openTasks.length}</span>
      </div>
      <div className={styles.taskCards}>
        {openTasks.length ? openTasks.map((task) => renderTask(task, true)) : <div className={styles.taskEmpty}>No follow-up is due right now.</div>}
      </div>

      {closedTasks.length ? <>
        <div className={`${styles.taskSectionHeader} ${styles.taskSectionHeaderSecondary}`}>
          <div><h3>Recently closed</h3><p>Completed, cancelled or expired follow-ups.</p></div>
          <span>{closedTasks.length}</span>
        </div>
        <div className={styles.taskCards}>
          {closedTasks.map((task) => renderTask(task, false))}
        </div>
      </> : null}
    </section>
  </>;
}

function NotesView({ leads, onOpenLead }: { leads: Lead[]; onOpenLead: (lead: Lead) => void }) {
  const notes = leads.flatMap((lead) =>
    (lead.notes ?? []).map((note) => ({ ...note, lead })),
  );
  return <><PageIntro title="Notes" copy="Human context that automatic tracking cannot capture: objections, preferences, promises and WhatsApp conversation outcomes." /><section className={styles.notesGrid}>{notes.length ? notes.map((note) => <button type="button" className={styles.noteCard} key={note.id} onClick={() => onOpenLead(note.lead)}><span>{note.lead.name.toUpperCase()} Â· {note.time}</span><h3>{note.author}</h3><p>{note.body}</p></button>) : <div className={styles.emptyStage}>No notes yet</div>}</section></>;
}

function HandoffView({ leads, onOpenLead, onOutcome }: { leads: Lead[]; onOpenLead: (lead: Lead) => void; onOutcome: (lead: Lead, outcome: string) => Promise<void> }) {
  return <><PageIntro title="WhatsApp Handoff Queue" copy="The OS knows the customer clicked Send to EmmyTech. Staff records the conversation outcome here until WhatsApp is integrated." tag={`${leads.length} awaiting outcome`} /><section className={styles.handoffBanner}><MessageCircle size={22} /><div><strong>Visibility boundary</strong><p>Do not count these as completed purchases. Record what happened after the WhatsApp handoff.</p></div></section><section className={styles.handoffGrid}>{leads.map((lead) => <article className={styles.handoffCard} key={lead.id}><button type="button" className={styles.handoffOpen} onClick={() => onOpenLead(lead)}><div className={styles.handoffTop}><div><span>WHATSAPP HANDOFF</span><h3>{lead.name}</h3></div><b>{lead.age}</b></div><div className={styles.handoffDetails}><div><span>Product</span><strong>{lead.product}</strong></div><div><span>Cart value</span><strong>{lead.cartValue}</strong></div><div><span>Voucher</span><strong>{lead.voucher}</strong></div><div><span>Status</span><strong>{lead.whatsappStatus || "Awaiting staff update"}</strong></div></div></button><div className={styles.outcomeBox}><span>Record manual outcome</span><div>{["Contacted", "Negotiating", "Paid", "Lost"].map((outcome) => <button type="button" key={outcome} onClick={() => void onOutcome(lead, outcome)}>{outcome}</button>)}</div></div></article>)}</section></>;
}

function whatsappHref(lead: Lead) {
  const saved = lead.whatsappUrl?.trim();
  if (saved && /^https?:\/\//i.test(saved)) return saved;
  let phone = lead.phone.replace(/\D/g, "");
  if (phone.startsWith("0")) phone = `234${phone.slice(1)}`;
  const message = lead.whatsappMessage?.trim() || `Hello ${lead.name}, this is EmmyTech. I am following up on your ${lead.product || "product"} enquiry.`;
  return phone ? `https://wa.me/${phone}?text=${encodeURIComponent(message)}` : "";
}

function LeadDetailDrawer({ lead, onClose, onMoveStage, onAddNote, onTaskOutcome }: { lead: Lead; onClose: () => void; onMoveStage: (lead: Lead, stage: number) => Promise<void>; onAddNote: (lead: Lead, note: string) => Promise<void>; onTaskOutcome: (lead: Lead, task: CrmTask, outcome: string) => Promise<void> }) {
  const [noteOpen, setNoteOpen] = useState(false);
  const [noteText, setNoteText] = useState("");
  const [saving, setSaving] = useState(false);
  const [localError, setLocalError] = useState<string | null>(null);
  const stage = stages.find((item) => item.id === lead.stage);
  const initials = lead.name.split(" ").map((part) => part[0]).slice(0, 2).join("");
  const profile = identityProfile(lead);
  const activities = identityActivities(lead);
  const isBlindSpot = lead.stage >= 5;
  const waHref = whatsappHref(lead);

  async function move(stageId: number) {
    if (stageId === lead.stage) return;
    try {
      setSaving(true);
      setLocalError(null);
      await onMoveStage(lead, stageId);
    } catch (error) {
      setLocalError(error instanceof Error ? error.message : "Unable to move stage");
    } finally {
      setSaving(false);
    }
  }

  async function saveNote() {
    const note = noteText.trim();
    if (!note) return;
    try {
      setSaving(true);
      setLocalError(null);
      await onAddNote(lead, note);
      setNoteText("");
      setNoteOpen(false);
    } catch (error) {
      setLocalError(error instanceof Error ? error.message : "Unable to save note");
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className={styles.drawerLayer} role="dialog" aria-modal="true" aria-label={`${lead.name} identity details`}>
      <button type="button" className={styles.drawerBackdrop} aria-label="Close identity details" onClick={onClose} />
      <aside className={styles.drawer}>
        <div className={styles.drawerHeader}>
          <div className={styles.drawerIdentity}>
            <div className={styles.drawerAvatar}>{initials}</div>
            <div>
              <span className={styles.drawerEyebrow}>MERGED CUSTOMER IDENTITY Â· {lead.identityCode ?? lead.id.slice(0, 8).toUpperCase()}</span>
              <h2>{lead.name}</h2>
              <p>{lead.phone} Â· {profile.email}</p>
            </div>
          </div>
          <button type="button" className={styles.closeButton} onClick={onClose} aria-label="Close"><X size={19} /></button>
        </div>

        <div className={styles.drawerBody}>
          {localError ? <div className={styles.inlineError}>{localError}</div> : null}

          <section className={styles.identityHero}>
            <div>
              <span className={styles.identityLabel}>Identity status</span>
              <strong>{profile.sources.length} records merged into one person</strong>
              <p>{profile.mergeConfidence} Â· Last seen {profile.lastSeen}</p>
            </div>
            <div className={styles.identityStage}><span>Stage</span><strong>{lead.stage}</strong><small>{lead.stageName}</small></div>
          </section>

          <section className={styles.identityFacts}>
            <IdentityFact label="Phone" value={lead.phone} />
            <IdentityFact label="Email" value={profile.email} />
            <IdentityFact label="Location" value={profile.location} />
            <IdentityFact label="First seen" value={profile.firstSeen} />
            <IdentityFact label="Owner" value={lead.owner} />
            <IdentityFact label="Source" value={lead.source} />
            <IdentityFact label="Referred by" value={lead.referrerName || "â€”"} />
            <IdentityFact label="Referral generation" value={lead.generation ? `Generation ${lead.generation}` : "â€”"} />
            <IdentityFact label="Original ambassador" value={lead.originalAmbassadorName || "â€”"} />
            <IdentityFact label="Follow-up status" value={lead.coolingStatus || "Contact allowed"} />
            <IdentityFact label="Lead health" value={lead.stage >= 6 ? "Customer" : lead.coldLead ? "Cold" : lead.atRisk ? "At risk" : "Healthy"} />
            <IdentityFact label="Time in stage" value={lead.stageAge || "â€”"} />
            <IdentityFact label="Expected progress" value={lead.expectedProgress ? `Within ${lead.expectedProgress}` : "â€”"} />
            <IdentityFact label="Cold threshold" value={lead.coldAfter ? `After ${lead.coldAfter}` : "â€”"} />
            <IdentityFact label="Last human contact" value={lead.lastHumanContact ? `${lead.lastHumanContact} ago` : "No recorded contact"} />
          </section>

          <section className={styles.drawerStatus}>
            <div><span>Current journey stage</span><strong>{lead.stage}. {lead.stageName}</strong><small>{stage?.short}</small></div>
            <TrackingBadge type={lead.tracking} />
          </section>

          <div className={styles.stageMover}>
            <div><strong>Move lead</strong><span>Manual change is saved to stage history.</span></div>
            <select value={lead.stage} disabled={saving} onChange={(event) => void move(Number(event.target.value))}>
              {stages.map((item) => <option key={item.id} value={item.id}>{item.id}. {item.name}</option>)}
            </select>
          </div>

          <div className={styles.stageProgress}>
            {stages.map((item) => <button type="button" disabled={saving} onClick={() => void move(item.id)} key={item.id} className={`${styles.progressStep} ${item.id < lead.stage ? styles.complete : ""} ${item.id === lead.stage ? styles.current : ""}`} title={`Move to ${item.id}. ${item.name}`}><span>{item.id}</span></button>)}
          </div>

          <section className={`${styles.nextActionPanel} ${lead.coldLead ? styles.nextActionCold : lead.atRisk ? styles.nextActionRisk : ""}`}>
            <div className={styles.nextActionIcon}><Clock3 size={17} /></div>
            <div><span>{lead.coldLead ? "Cold lead" : lead.atRisk ? "At risk" : lead.nextTaskDue ? "Action due" : "Follow-up status"}</span><strong>{lead.nextAction}</strong><p>{lead.nextTaskDue ? `${lead.nextTaskDue} Â· ` : ""}{lead.priority} priority Â· Owner: {lead.owner}</p><small>{lead.coolingStatus || "Contact allowed"} Â· {lead.contactAttempts ?? 0} contact attempt(s)</small>{lead.coldReason ? <em>{lead.coldReason}</em> : null}</div>
          </section>

          {isBlindSpot ? (
            <section className={styles.blindSpotNote}>
              <MessageCircle size={16} />
              <div><strong>Manual visibility boundary</strong><p>WhatsApp activity after the handoff is not automatically visible. Staff must record the outcome here.</p></div>
            </section>
          ) : null}

          <section className={styles.drawerSection}>
            <div className={styles.drawerSectionHead}><div><h3>Follow-up tasks</h3><p>Tasks appear only when the follow-up window is due. Progress cancels stale tasks automatically.</p></div></div>
            <div className={styles.drawerTaskList}>
              {lead.tasks?.length ? lead.tasks.map((task) => <div className={styles.drawerTask} key={task.id}>
                <div><strong>{task.title}</strong><span>{task.due}{task.expires ? ` Â· ${task.expires}` : ""} Â· {task.owner}</span><p>{task.description}</p></div>
                {task.status === "open" ? <div className={styles.drawerTaskActions}><button type="button" onClick={() => void onTaskOutcome(lead, task, "Contacted")}>Contacted</button><button type="button" onClick={() => void onTaskOutcome(lead, task, "No response")}>No response</button><button type="button" onClick={() => void onTaskOutcome(lead, task, "Completed")}>Done</button></div> : <span className={styles.taskOutcome}>{task.outcome || task.status}</span>}
              </div>) : <div className={styles.emptyStage}>No follow-up task is due yet.</div>}
            </div>
          </section>

          <section className={styles.drawerSection}>
            <div className={styles.drawerSectionHead}><div><h3>Activity history</h3><p>What this identity has been doing across the funnel.</p></div></div>
            <div className={styles.fullTimeline}>
              {activities.map((activity, index) => (
                <div className={styles.fullTimelineItem} key={`${activity.title}-${index}`}>
                  <span className={`${styles.timelineDot} ${styles[activity.tone]}`} />
                  <div className={styles.fullTimelineCopy}>
                    <div><strong>{activity.title}</strong><time>{activity.time}</time></div>
                    <p>{activity.detail}</p>
                  </div>
                  <TrackingBadge type={activity.tracking} />
                </div>
              ))}
            </div>
          </section>

          <section className={styles.drawerSection}>
            <div className={styles.drawerSectionHead}><div><h3>Notes</h3><p>Sales context added by staff.</p></div></div>
            <div className={styles.drawerNotes}>
              {lead.notes?.length ? lead.notes.map((note) => <div className={styles.drawerNote} key={note.id}><div><strong>{note.author}</strong><span>{note.time}</span></div><p>{note.body}</p></div>) : <div className={styles.emptyStage}>No notes yet</div>}
            </div>
          </section>

          <section className={styles.drawerSection}>
            <div className={styles.drawerSectionHead}><div><h3>Commercial context</h3><p>What sales needs before taking the next action.</p></div></div>
            <div className={styles.snapshotRows}>
              <div><span>Product interest</span><strong>{lead.product}</strong></div>
              <div><span>Voucher balance</span><strong>{lead.voucher}</strong></div>
              <div><span>Cart value</span><strong>{lead.cartValue}</strong></div>
              <div><span>Last known action</span><strong>{lead.lastAction}</strong></div>
              {lead.blocker ? <div><span>Current blocker</span><strong>{lead.blocker}</strong></div> : null}
              {lead.whatsappStatus ? <div><span>WhatsApp status</span><strong>{lead.whatsappStatus}</strong></div> : null}
            </div>
          </section>

          {noteOpen ? <div className={styles.noteComposer}>
            <label htmlFor="crm-note">Add note</label>
            <textarea id="crm-note" autoFocus value={noteText} onChange={(event) => setNoteText(event.target.value)} placeholder="Add objection, promise, preference or WhatsApp contextâ€¦" />
            <div><button type="button" onClick={() => { setNoteOpen(false); setNoteText(""); }}>Cancel</button><button type="button" disabled={saving || !noteText.trim()} onClick={() => void saveNote()}>{saving ? "Savingâ€¦" : "Save note"}</button></div>
          </div> : null}

          <div className={styles.drawerActions}>
            <button type="button" className={styles.primaryAction} disabled={!waHref} onClick={() => { if (waHref) window.open(waHref, "_blank", "noopener,noreferrer"); }}><MessageCircle size={16} /> Open WhatsApp</button>
            <button type="button" className={styles.secondaryAction} onClick={() => setNoteOpen((value) => !value)}><Mail size={16} /> Add note</button>
          </div>
        </div>
      </aside>
    </div>
  );
}

function IdentityFact({ label, value }: { label: string; value: string }) {
  return <div className={styles.identityFact}><span>{label}</span><strong>{value}</strong></div>;
}


