'use client';

import { useActionState } from 'react';
import { saveMarginPolicyAction, saveSalesAuthorityAction, saveSalesSettingsAction } from '@/app/modules/sales/actions';

const initial = { success: false, message: '' };

type Settings = { company_default_margin_percent: number; company_archive_email: string | null; quotation_valid_days: number };
type MarginPolicy = { id: string; policy_scope: string; category: string | null; inventory_item_id: string | null; minimum_margin_percent: number; inventory_item?: { name?: string; sku?: string; category?: string | null } | null };
type Authority = { user_id: string; authority_level: string; discount_limit_percent: number; is_active: boolean };
type User = { id: string; name: string | null; email: string | null; role: string | null };
type InventoryItem = { id: string; sku: string; name: string; category: string | null };

export function SettingsWorkspace({ settings, marginPolicies, authorityProfiles, users, inventory }: { settings: Settings; marginPolicies: MarginPolicy[]; authorityProfiles: Authority[]; users: User[]; inventory: InventoryItem[] }) {
  const [settingsState, settingsAction, settingsPending] = useActionState(saveSalesSettingsAction, initial);
  const [marginState, marginAction, marginPending] = useActionState(saveMarginPolicyAction, initial);
  const [authorityState, authorityAction, authorityPending] = useActionState(saveSalesAuthorityAction, initial);
  return <div className="mx-auto max-w-[1400px] space-y-5"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-slate-400">Admin commercial policy</p><h1 className="mt-2 text-3xl font-black text-[#032489]">Sales Settings</h1><p className="mt-2 text-sm text-slate-500">Future decisions use current settings; frozen historical transactions and issued documents never get rewritten.</p></div>

  <div className="grid gap-5 xl:grid-cols-2"><form action={settingsAction} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black">Company defaults</h2><div className="mt-4 space-y-3"><label className="block text-xs font-bold text-slate-500">Default minimum Gross Margin %<input name="company_default_margin_percent" type="number" step="0.01" min="0" max="99" defaultValue={settings.company_default_margin_percent} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /></label><label className="block text-xs font-bold text-slate-500">Official company/archive email<input name="company_archive_email" type="email" defaultValue={settings.company_archive_email || ''} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /></label><label className="block text-xs font-bold text-slate-500">Default quotation validity (days)<input name="quotation_valid_days" type="number" min="1" defaultValue={settings.quotation_valid_days || 7} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /></label></div>{settingsState.message ? <div className={`mt-3 rounded-xl px-3 py-2 text-sm ${settingsState.success ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'}`}>{settingsState.message}</div> : null}<button disabled={settingsPending} className="mt-4 rounded-xl bg-[#032489] px-5 py-3 text-sm font-black text-white">Save defaults</button></form>

  <form action={marginAction} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black">Minimum margin policy</h2><div className="mt-4 grid gap-3"><select name="policy_scope" className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="category">Category policy</option><option value="product">Product override</option></select><input name="category" placeholder="Category (for category policy)" className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /><select name="inventory_item_id" className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Product (for product override)</option>{inventory.map((item) => <option key={item.id} value={item.id}>{item.sku} · {item.name}</option>)}</select><input name="minimum_margin_percent" type="number" step="0.01" min="0" max="99" placeholder="Minimum Gross Margin %" className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /></div>{marginState.message ? <div className={`mt-3 rounded-xl px-3 py-2 text-sm ${marginState.success ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'}`}>{marginState.message}</div> : null}<button disabled={marginPending} className="mt-4 rounded-xl bg-slate-900 px-5 py-3 text-sm font-black text-white">Add margin policy</button></form></div>

  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black">Active margin rules</h2><div className="mt-4 flex flex-wrap gap-2">{marginPolicies.map((policy) => <span key={policy.id} className="rounded-xl border border-slate-200 px-3 py-2 text-xs"><b>{policy.policy_scope === 'product' ? `${policy.inventory_item?.sku || ''} ${policy.inventory_item?.name || 'Product'}` : policy.category}</b> · {Number(policy.minimum_margin_percent).toFixed(1)}%</span>)}{!marginPolicies.length ? <span className="text-sm text-slate-400">No overrides yet — company default applies.</span> : null}</div></section>

  <div className="grid gap-5 xl:grid-cols-[420px_1fr]"><form action={authorityAction} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black">Sales authority</h2><div className="mt-4 space-y-3"><select name="user_id" className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Choose user</option>{users.map((user) => <option key={user.id} value={user.id}>{user.name || user.email || user.id}</option>)}</select><select name="authority_level" className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="salesperson">Salesperson</option><option value="manager">Sales Manager</option><option value="admin">Admin</option></select><input name="discount_limit_percent" type="number" step="0.01" min="0" max="100" placeholder="Maximum discount %" className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /></div>{authorityState.message ? <div className={`mt-3 rounded-xl px-3 py-2 text-sm ${authorityState.success ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'}`}>{authorityState.message}</div> : null}<button disabled={authorityPending} className="mt-4 rounded-xl bg-[#032489] px-5 py-3 text-sm font-black text-white">Save authority</button></form><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black">Configured team authority</h2><div className="mt-4 divide-y divide-slate-100">{authorityProfiles.map((profile) => { const user = users.find((u) => u.id === profile.user_id); return <div key={profile.user_id} className="flex items-center justify-between gap-3 py-3"><div><div className="text-sm font-bold">{user?.name || user?.email || profile.user_id}</div><div className="text-xs text-slate-400">{profile.authority_level}</div></div><div className="text-sm font-black">{Number(profile.discount_limit_percent).toFixed(1)}% max discount</div></div>; })}{!authorityProfiles.length ? <div className="py-5 text-sm text-slate-400">Only application Admin authority is active until Sales profiles are added.</div> : null}</div></section></div>
  </div>;
}
